### ISSUE TITLE
breakpoint

### ISSUE THREAD

**Issue by gcclua** [jgressmann/pokemon#1]
good job, but can not set breakpoint on my qtcreator 3.5.1 custem build, and my project is a makefile project,miss something? thanks

QML Debugger: Waiting for connection on port 14026...
Receive
0000002e0051004400650063006c006100720061007400690076006500440065006200750067005300650072007600650072000000000000000100000007000000140056003800440065006200750067006700650072000000240051004400650063006c00610072006100740069007600650045006e00670069006e0065000000160051006d006c004400650062007500670067006500720000001a00440065006200750067004d006500730073006100670065007300000026004400650063006c006100720061007400690076006500440065006200750067006700650072000000180051006d006c0049006e00730070006500630074006f0072000000300051004400650063006c0061007200610074006900760065004f0062007300650072007600650072004d006f0064006500000010
.QDeclarativeDebugServerV8Debugger$QDeclarativeEngineQmlDebuggerDebugMessages&DeclarativeDebuggerQmlInspector0QDeclarativeObserverMode
Send
660000000000002e0051004400650063006c0061007200610074006900760065004400650062007500670043006c00690065006e007400000000000000010000000100000014005600380044006500620075006700670065007200000001000000010000000c
f.QDeclarativeDebugClientV8Debugger
Receive
0000001400560038004400650062007500670067006500720000001a000000075638444542554700000007636f6e6e656374ffffffff
V8DebuggerV8DEBUGconnect����
Send
3600000000000014005600380044006500620075006700670065007200000016000000075638444542554700000007636f6e6e656374
6V8DebuggerV8DEBUGconnect
Receive
000000140056003800440065006200750067006700650072000000590000000756384445425547000000097638726571756573740000003d7b22736571223a302c2274797065223a2272657175657374222c22636f6d6d616e64223a2276657273696f6e222c22617267756d656e7473223a7b7d7d
V8DebuggerYV8DEBUG  v8request={"seq":0,"type":"request","command":"version","arguments":{}}
Send
b90000000000001400560038004400650062007500670067006500720000009900000007563844454255470000000976386d6573736167650000007d7b22736571223a302c2274797065223a22726573706f6e7365222c22726571756573745f736571223a302c22636f6d6d616e64223a2276657273696f6e222c2273756363657373223a747275652c2272756e6e696e67223a66616c73652c22626f6479223a7b22563856657273696f6e223a224c756120352e31227d7d
�V8Debugger�V8DEBUG  v8message}{"seq":0,"type":"response","request_seq":0,"command":"version","success":true,"running":false,"body":{"V8Version":"Lua 5.1"}}

**Comment by jgressmann** [comment]
Hi there,

yeah sorry, that part was missing in the README.

You need to set the environment variable QTC_QMLDEBUGGER_FILEEXTENSIONS to the file extensions used by the QML debugger i.e. ".qml;.js;.lua".

Cheers,
Jean
