### ISSUE TITLE
pokemon in the multi thread

### ISSUE THREAD

**Issue by gcclua** [jgressmann/pokemon#3]
Hi, jgressmann

```
     pokemon is great, but it can not break in the multi thread 
```

**Comment by jgressmann** [comment]
Hi could you elaborate? Lua doesnt have  threads afaik.

Cheers, Jean

**Comment by gcclua** [comment]
Hi, jean

```
     I am test with a main thread , and 3 logic thread,  Each thread has its own virtual machine(lua_State*),  the breakpoint will be trigger in the main thread , never be trigger in the other 3 thread.   

thanks 
```

**Comment by gcclua** [comment]
Hi, jean

```
    the breakpoint set  only set into     DebuggerState::m_Breakpoints  of  first lua_State registe in pokemon, Can copy from the first DebuggerState::m_Breakpoints to the other DebuggerState ?
```

thanks

**Comment by jgressmann** [comment]
Hi,

Maybe some background on how pokemon works is could help here. Pokemon
connects a Lua state to QtCreator by pretending to be Javascript (or QML)
application. Since there are no threads in JS, there is no thread switching
support in QtCreator for Javascript.

To debug a thread other than the main thread you need to make that thread
the 'selected' one using luaD_select(LuaState*).

Hope this helps.

Cheers,
Jean

**Comment by gcclua** [comment]
Hi, jean
             thanks for reply, but breakpoint info is send to pokemon on main thread run, the logic thread is run after, if ignore the main lua_state registe to pokemon,  the s_Pokemon->Selected will be equal NULL, 
        " // call into active state
          response = s_Pokemon->Selected->ProcessReques "

if let main lua_state registe to pokemon, the breakpoint info will store in the main DebuggerState

**Comment by gcclua** [comment]
Hi, jean

```
     OK, got it , use luaD_select(LuaState*) and update pokeman.cpp like follow: 
```

# 

#if 0
        std::shared_ptr<DebuggerState> state(new DebuggerState(L));
        state->Lock();
#else
        static DebuggerState\* g_firstDS = 0;
        DebuggerState\* newDS = new DebuggerState(L);
        std::shared_ptr<DebuggerState> state(newDS);
        state->Lock();
        if(!g_firstDS)
        {
            g_firstDS = newDS;
        }
        if(g_firstDS != newDS)
        {
            for (auto\* pBp = g_firstDS->m_Breakpoints.load(); pBp; pBp = pBp->Next) 
            {
                newDS->m_Breakpoints.store(pBp);  
            }
        }

# #endif
